Maintain code block background colour
Bioconductor/BiocStyle pull request #87
Opened 2021-03-14 22:02 UTC by grimbough

This primarily tries to fix the code block styling in #86 

**rmarkdown** now injects `pre:not([class]) { background-color: white; }` into the HTML head at https://github.com/rstudio/rmarkdown/blob/9c1498806fef286f3891238a8298e064969c8aec/R/html_dependencies.R#L78

Previously this was found in the HTML page template, and we removed it there.  Now we have to remove it later.

---

I also added myself as a contributor in the `DESCRIPTION` file and changed to the `Author@R` format so I could include the ORCID.  Feel free to ignore that commit if you don't agree.

2021-03-19 12:29 UTC, aoles commented
Thanks a lot @grimbough for providing the fix. I will have a closer look over the next few days. Cheers!

2021-03-26 23:51 UTC, aoles requested changes
Thanks again for the fix, it does the job!

However, there seem to be a problem with the formatting of the `Authors@R` field. When I try installing the package I get 
```
Error : Invalid DESCRIPTION file

Malformed Authors@R field:
  formal argument "role" matched by multiple actual arguments

See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.
```

Similarly, R CMD check throws
```
* checking for file ‘./DESCRIPTION’ ... ERROR
Required fields missing or empty:
  ‘Author’ ‘Maintainer’
```
Do you think you could fix it? It would be great if you could also include my ORCID as well: 0000-0003-0285-2787.

Cheers,
Andrzej

2021-03-27 09:33 UTC, grimbough commented
Sorry, that was a dumb mistake. Should be fixed now.

2021-03-27 09:54 UTC, aoles commented
Thanks! The package now installs, however, `R CMD check` still complains, any idea?
 
```* checking for file ‘./DESCRIPTION’ ... ERROR
Required fields missing or empty:
  ‘Author’ ‘Maintainer’
```

2021-03-27 11:41 UTC, grimbough commented
Weird, it didn't throw that locally. I'll check in a bit.

2021-03-28 08:51 UTC, grimbough commented
I'm afraid I can't reproduce this problem.  Here my output from running `R CMD check` on the source tarball.

```
-> % R-dev CMD check BiocStyle_2.19.2.tar.gz 
* using log directory ‘/home/msmith/Projects/BiocStyle.Rcheck’
* using R Under development (unstable) (2021-03-18 r80099)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘BiocStyle/DESCRIPTION’ ... OK
* this is package ‘BiocStyle’ version ‘2.19.2’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘BiocStyle’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... NOTE
Unexported object imported by a ':::' call: ‘rmarkdown:::partition_yaml_front_matter’
  See the note in ?`:::` about the use of this operator.
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking sizes of PDF files under ‘inst/doc’ ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘run_tests.R’
 OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ...
  ‘AuthoringRmdVignettes.Rmd’ using ‘UTF-8’... OK
  ‘LatexStyle2.Rnw’ using ‘UTF-8’... OK
 OK
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE

Status: 1 NOTE
See
  ‘/home/msmith/Projects/BiocStyle.Rcheck/00check.log’
for details.
```

2021-03-28 09:33 UTC, aoles approved these changes
Now I've made the stupid mistake of running `R CMD check` on the source dir rather than the tarball, I'm sorry for that. 

Everything is fine now, feel free to proceed with the merge.

Cheers,
Andrzej

2021-03-28 17:40 UTC, merged

2021-03-28 17:45 UTC, grimbough commented
Done and pushed to BioC.  Thanks for the review.